language: python
python:
  - "2.7"
  - "3.4"

env:
  - DJANGO="django<1.7"  # 1.6.x
  - DJANGO="django<1.8"  # 1.7.x
  - DJANGO="django<1.9"  # 1.8.x
  - DJANGO="git+git://github.com/django/django.git@master#egg=django"

# command to install dependencies
install:
  - pip install $DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors

# command to run tests
script:
  - coverage run --source=jstemplate jstemplate/tests/project/manage.py test
after_success:
  - pip install --quiet coveralls
  - coveralls
